"""empty message

Revision ID: 0360a97a723b
Revises: 8ae28c88fc8f
Create Date: 2023-08-12 18:15:27.129044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0360a97a723b'
down_revision = '8ae28c88fc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
